# Generated by Django 4.1.7 on 2023-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_activity_activityrule_point_position_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(db_index=True, default=0, max_length=255),
        ),
    ]
