# Generated by Django 4.1.7 on 2023-04-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_score_name_alter_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='name',
        ),
    ]
