# Generated by Django 4.1.7 on 2023-04-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_remove_score_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees'),
        ),
    ]
