# Generated by Django 4.2 on 2023-04-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_empusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpUsers',
        ),
    ]
