# Generated by Django 4.2 on 2023-04-30 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_empusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='empusers',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empusers',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
