# Generated by Django 4.2 on 2023-04-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_rename_emp_password_empusers_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='pointable_id',
        ),
        migrations.RemoveField(
            model_name='point',
            name='pointable_type',
        ),
        migrations.RemoveField(
            model_name='point',
            name='transaction_type',
        ),
    ]
