# Generated by Django 4.2 on 2023-05-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0015_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
